sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        CXr9uelCjc3rrywx7g0/4t7OgWczKlAAf353xR6JOUMvTxUICrGkm9hZHE9ggwz8WjPo26ZkoOeRBolLFa5YNNRASfISymPctsUJyKCiFwWvmbHfKVQ5O0ohbEq+UPeZpoghYqdoZw9WYPVqt6ZU8dyq2uGRQjPzw55u/BORyPqrFmiyYHg218H1q0N3tC9V0SC8qLhTYsWJBuuGN5vteDLYF17ThxNsB5UFEONgpzBtXebTg3o9fOpKLnI8GYjGlCQhuoJV3MjtS/FRvwU5nYqodIkTObM6LJN65Ah5bs3t4vQCKuZqj2MdvcjvVcZX4hIQBrXLbLPLJ5m34LStQLtSBOtwRVPvkhrDlgJT3+vfwMJjAYrurqFPiA51BRi7lLLg1vcnq1cWnftsM9IrSj0FNSlDvTbUYb9CWGbJIyYR+Uw+CdU3G0q4PiQ6UgzXPfmmI78oNSu3ZlL29xslfdYZWJmiEQ0A0XTT8KxOF2KY2y9wBq9+WS/e0X+GKnlTeDXAFCq75xV66HPkTuHFGeyz2uWejUvgr4fDhheRnJvx5/cojxEYrGaMJibzgCX2Pr+8RV8kkVp6QvMyuk0SzWXcivUyXQtECjnmXEHpfSBPs+RmiP4pJFkN+JOrLJY9xi/xioEvBwBOsu8xvhrPMM8fg6j+59dtIO8/fz+zTwU=
    - secure: >-
        KtoeuOpCQNvtiah06pvWyE8kPXAVQlzJxSfzWXdrH25n2KsH8PRzQw6HToBS8GM6Ic+kX77Ctz1ke8I6e4zEivaUEg6CTrLScu7VCUFnvx+19Iw5CShU0Z1InhIfpbASl+LSHrnCmzXwp6aZm+CX79oePRNryz3qIj0rDq11/GUiC4dOmS8aPi/S+7zQXUw5dtjIoic3bOO/4rjhvzsShX1MWc8JR24+BzSafYVlcvZdzf2LYSN2Yj8WC7D3AziELTm6vchR6jxDWFliuxojNdv3VqBEdcaXvel7583GYyXrIt+xFoUagZCyO7usfzukbHodADww3CXNdSEYDauxlpgp6qn1U9RcSBDhRE/D0aHojrZ5iatSImQix0ozVglhGkB2PXMLUEN9W4aV9/0RfFRTh2EhCsWcfs0FZbnk7ik1og/6dr4GdAOgjcmZdeeFD/qOSk1G517FeCm59RgYH6+2xOTdYdihT6HIU+nNS03q4f1C9l1745yXMuevs/8pwcd5sws0mljuwr6CHtdCC/SKQdiM1CfwVlpRAi2OhSjbU9EQ33WjLQbbIDewpnerP711gWydjLuvWMls5FWNgrAIBRguqrLgxLqGjRcW1s8TAt27fccHg7clAnAL8cfOQHHuGo+Fb2b7HQvwwjVedlsx3W/tM41XGUL+s5myjZQ=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
