sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        kDTVNQBcK07d53Zf+JYbImbYLKUVmkeiUet9WNQ36IUWVJk7jwhpI9hrSX4RlDokNVJzy+wYa1Adms4UwEj+exCh8np/UgxFRXKknW2/hB0b6sw6lNrS6rHxwZ8Ji2J05m/hG3PP5Z91AAvpmneoGZiMHHZwbaU6pnkQEfaA9UDm17IxpVb5dNcaqmanxWphx463hXPWrQuX82l8AanXY1Dic8ypPfgKBvwGIa2RMB3Bo8p3qSp3Bzghjz7m0EzqVy1ajR+sFRfmfci/T+TsxSz9rGVA8A4L7+xbJm8PF1nw7zaemL2c36+xBSOd34hyi9fZ4/xlSL6RnZyn4njALcSWbfL/TZHUMRwMxK2CNyFcuGTaOUXxO9/03DUF+syLq7tpyEF4/p79wMvnzIIpTsh9V9zdktggRD/uWqA5ThqZ2Ohlcn3Ew6oJFYDXQbnjG8FTuryZGvjW5A6X5UDwbs19xslronDRQRLqAjYhNuLX+n44Sl/91uPupwg/JS5XhHHLFopTuQd/zxslzzIhhipN2iHYhSpOlnfyRLW8Jh5jXRventavuNqfFLl5DZKsidTPOTQ1Hmr0DcvAPgogyY1f8jVdl3/tnNniHvlZA9Nb55fLaNm1efUWZhHJfR9mkcCFb8v7RQamPivgKSpl/Pshfkh2g+o47F0I1r1ynBw=
    - secure: >-
        cWrMQhBPDJqo7z9JckV5NqvgRFGU8qDMZ6fnTBRq+YNTRRvBk4TL9xtoPcUx0ie/jjUxohZlp50KmVDIA0+pGAcIw0gFAZiav06o5Ab4o3R0cPaI4UwSsL3ckdN27vac/GtM0CBGPluZjn/taBTgaiWtPI3zJ/HuE5mplHk3LZliGazHkZd6hcHF6gDK1Oik1larSYx7mT3uWSdYDGiI5QLExXQE/7NjsJoWlUIE5BNoyHWRKIgtJIHs7Vpt0F9aEv5hXKmmOQDPfezACuQNI3u4rynv0NuiLcZ7BaoNReNFuSKC5P6AeyZzgJ9B574LXc6ZfGZRiNOqlSgVK9P6j8x/9CKAGVVXhMYjcAToA3QBlSeJKo6Qg3FsVkUw6jfSODmtsY+apEyDLlhPMzjF+fm1DQGwyE9jcdg2UtyPQBCdHKzvpILh0CdC6cnuIChWC0lFsFMMp/5Hqf+lQeYfUkajl8PES0QEvB/hNqGxBQMQ3yMy1DJHtb++g/BoKRyc37KARK3q1d7Tnwp9MkDdUMMOcgPAGiTkXB5nfAtFJZH1w4t4Ql6ncYUHNFl8xucpkiHKSIARmscPnkc9T3No6NStlsOlEzKVCEY4QaXbInU793oM+Hfs/0D2UDN+dWNQ9upwKEshlgOqgI6dZFSLKP6aGBMcK6fl4k1lVgoJXjc=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
