sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        vt3ros2qwTOI3Ohryw3MyOgxNswOaQlwxSaWLYJDKOTsxoqwODkdkB6KIJXAAUS/Op5rbGRofdj6V5oYUUIOHwNsPBVEYjxA5DB6SGmxrZ3kodE03LiEEjxZFex4fOiqjOJx0TdLNKrJRiJn+9A3V1WDTKAmRNhFFZxKz7GgSH447sLZ8WNlga2DSTNc6xQ23NJvweonpZAyqxGknCxEErwOE0d2D4qXD07uPonC0pTfd2s8E1rpbOx95/LVKxbVqyuvaYohE38k+RuNSoMV0ZQJ2+39VuavlbxrjGfuUdjt3PqbZqgLWybVDemJDrP57GgNPU6LVJt99KuUlyN12kSZ76N1DPntha7zVG/eo1PJVVhJG8btyg1egSGmPnF/PTEyi6NWvcyGTxmrPldpeXyMsfQX5nb9Znkqp+2i3yuRJRRYZ3gUFveZwhU+42tuhNdZrGVuc1L0EN89qYchs5PiZ3aEDYtYWYyWkJCs5lWqOTZoCRF2y0MQNPLtNW158jURPHoGEnk08Btgg73P0JsuZ/ST+t54Zer4f72VxKFYGyYNPjfqNfdNS5QW34E4XYqBUCkZC6pG78+U01r1CAFz1T5awhH3QTUpwdHhyDYtBsRJ6rAqXGxeeTFZYBQ9gxfa2or8HslDfgMrK81H/1Qk/Za22Vz0t4Sw9FQz6Kw=
    - secure: >-
        MFt7rzd2+b/WoX3NQ3osZ3Hs2wmLwZGeSY2juAZAFlUPyocWtA0SiJDa1ukp60CJrZ6zRv3a4zWo9OrY75lSTqtWG0MyY3fygroAvV06dL3yDLauqIIqzGwJfdnxSk2rKJ8zDtlAkYEK6RbqCfsyAAZiCcIt1wISRAmnGZl4WERfOfEvDBVoqR73Jq6aSy4DXdduwQFaWK1jqC7IFXw5IQrb0IeSE7jPT1NKW6AyrminGrpx8mxHprDdD7rH6vgYvvsmXC19OYqOpDnDTvpuqSuu1IWrrOdixCSUeAydBblNRPNlA/XbkO1nkF0UKa64ue3oFMgxKSCAOYkMMTM0vPn8ipYmxu5G4n1g7IzJaMCy9ltmcSA/YJzMH5KvyID2y1G2XvgKJJh1LE3bA83UTKWFEOEbu94VkCzMbDAI8s+fwTxXgtUvKLCkobI6MSuhbvvw2Hv06Z6jQCcB0vcbWv3EAhOTJeKL/9MEFGK47NGbk9pXcT3zYJNzzfTZ56yxws8nf5UenOxBPQ+xR1V0DNZEuCqn4V7Du+oQ+3z+kEMRVxRYVY8dGZmdE7nkfXe+EtVrLwKhtxXNWDLG5v0xYEHntqhB0YlGhqbTi3aPCYABAY3ZDt+MF+0lZcW76MBI5k9b4v+cKxNappzAmkchcEvJIkfm/4BCRE2IZeyol6I=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
