sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        FD4054+BXH+dt7Tj5ReSd+rENbyfpBk7xvZ/+epq5y2XxOQmopEaZLh2M/N1URMQYnB9ady5dWyyhArG//ZGetjfWhFj5fsFc0/EHvxmf6XD0DTjuJ2G4dkrD3SqtxB1a1dhgdP89akUyNxf7YKCclz58Z7bHgUJyG486TWo7wcEchEyqb71vsUCnhqoCLX3MJOy21rC3c4kntvVhME4NJULaJxPfy2HrqjaU1PycSPueuq/4UE3DqRe8TV1x5YH9CLkKVi6FFDIGM97xdo05QrukPV3iHZ1jQJ6vUz1r8yuxAtPe5tpgrFucsKHYdIj5iEfeO7krwdyqI7US+ARi5rHX7a0whdHt6/Tk7l1+/QPAt1y7JQIFi8krhE/Gy9bLUTefieOWaV+mi8+yMFS04UJBjHZ23CuacWSwRJWK0e0vo1um9hxqZIMWcz/9mM03lQnryCCbHKlgdjHrVGteVrFrQiF1wIyKvbLSy4ONK9JtAtZC4wnbtby+P0pMtvQp3MWSvf6KMvRLyK4bFpCt6EYOGZVAyiZBrL0B9VLo0Od+4Nf37+AJwMe2htX3EAfjs8IAcnulNS+UoIU7LK2rb0AINQEdI0+1kxiIbp/V6S7ffy7D8YBbAJpKqLRp/EtVdecY7ADS//PgpZ9WivKLbTLZPQZNcadJzQZVYLgn8s=
    - secure: >-
        ao6PaSz47kQtA6aGttT1Ttq4UNkmHAWtDm8o6keZNBRM0NUbjEgnX0cUGIqMEySpLjpyUvH8j5NL6gKdHdbUicG0UK2R60jOGkOeC9aOdNp9TgHzryXDvA1xkz9PV+m02yjc3T7TWTh2pAVYBed71DiRijSUbSK7chTxO73EdLLUatajBPbTbS574PfIgvWvx4LzNBZZYJW0eLM5aypJjuqBreeI+5yCefEcmpVOExSbIQnXBYpSs2NCxk/lnR99brFC3rWPiVXzZyzENJAQgHJ0AhaI/okE64e2EeGMnNxUCBUyljiBr3+OACbKn1ZcAZHZlaqMjFACBML/lN4AyVOyoLXASWupUSvehV6UjPh9hJyIQF5RRoTPEfxKB7stKKL4+9bZ36RFaowAPjoaJBeAeksunU82pKsuX+IgAksHSlSUyDHHVH1WrbxTMCkKinG0r4L334MVFwONCS960obKSwT2dng2C4ZDOY8IMQ24zgXjpUYvAPz2wyt8VzEAnTYg6NC7x2kU3H4f/UTaLW6nWxzyRNVk0rOnng3BuFRqjl8+O3afsx3gO73I2EhwfSz+3oN1TQTQjs+C6W9HoPJNMLCwBg92K82+Gj0J1Idki+dE9b/MuJ1dLGq6stgrGXG0fONf+MJ5w+HM/T2ke2ac/WLYmxWW/pkxInd+lec=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
