sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        jBBWtvudjUZYSYGkRfwnd8iX9qE5Zz8yY54XazwW9qXP1JWuaESu6SwWfkzqVIyeIG7EpiGtGTTGu5XlzCs2X2W3uIRvAekyo3CqjldMstW5SYcCC/5l1zWNl1auhz77scTZCVwbgOx9cLUHgrh7k+x8C4tMyz1EYNvnTSIZLuvfjbZ+ktq+dqxJNRyaI7ld4KXdFrYp0p/Jue3TjOyTVoXqmz1+6GI8ZIz4yrCgeZcci8UTJ57JwObpj8xOkC5uru2t5eBqI67o1m3CBv8z/6c9yMNdcc/7u9LGkPv/QXTylIUTS272IfIAojyPVFyvqwGzu6vgZ/hWWEPQVq03xt7DsCGXRymH3a7B6RkIt/Yi9qWk48vKuwbm+ucyV9OmZGuKi6L66W4xkRpvcGu1TePdCAI2bPu21lq6Y78lsS/iiv8PXogQyM00aJbVK3NZUeLFBVacZ3MuZzMiqy3zLERZ90l+OeDs9b0jAu5p0b5vNMnEgZMCCGeDAiKx1fkYkLRoNr6r2wVmc5MmCGi0RFI0wncnx+lN00vFUqtIArFT8dOZbjb8NrXpGkZxylyJt3XTGAT16ycRJKiNRIU+SPMVFW1q2aUtwxIA0L5u4uV4YZHI3cYPxeItgJSIptWLqVchOoWKeqEhqseVTl313Cy7bQcBgYR1JRkS7aS5GT8=
    - secure: >-
        UelcimH3BLGUDTjbr+ZdkrPfk85pxbHHXkMaYPUi3gU7ttVFlL1YBzCwCTthH1dRsNYE3AdsVoaemmGqgEukzBWLK+XdREJJyq/nKj1yrBKlyV+75wwqGwUNlpHQG7BG+yysl8gKDxkb2Xet53yJRp4wfXRN1xaXGnrSUK/Cjour4uk6V6Ti8aW+W3lXH0SfLzR5zrdRbQCiRc18lkPruHr7oPCsEhmU7eX56Pw2j52RqZ9mQrF6diaBQZ3v7xmFUybU/D5JeuJeFrOZCKqANpZhy79EwCp7FKHs2EfIK7Swl74IO0JGMEzuP09uFs9dGRZi3iP45MLMvT7bZsvTEk749fROiYnEJM+V6Ld10skNC8ggw/bBZKx6v1v0RBr60hBe4vdhwnRikr8oyB9XnxazGWmV3Mmi2Ljaniq1DWqGyCNLu2o2u5MqeyfZ29/WhF2jm79DhNL9+B9BUyXdVZ/jULV1vQeoJcG7/qPi+ax5DN5xiSMM9noGknqfEhrJ4QOhBoJ3gJ7c4aSaKTjnoLYlnIWLjaT+DYY6b1Vt1TNsiKaNDrL5sPMl4i1GN0CSLnJFIfbf03rRzGoLFPLgG1gzI0rduoBH97PSR5sGFjJDm0UQAHDeNKRULH1RDy2uGEsgdWorFexo1UiLvQ+vat4M5hzG4IZYcwxOUu3gVjQ=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
